### ISSUE TITLE
How can i hide this menu?

### ISSUE THREAD

**Issue by VoQZHD** [pacocoursey/Opus#8]
![image](https://user-images.githubusercontent.com/45748775/55951898-264f2f80-5c7a-11e9-944d-176241cf6bee.png)

**Comment by VoQZHD** [comment]
Looks awful

**Comment by pacocoursey** [comment]
Hi, would you mind posting a full size screenshot? I believe that menu is present on all Electron applications built for Windows. So this is probably a wont-fix, but I can look into it.
